---
simulation_campaign: /gpfs/bbp.cscs.ch/project/proj83/scratch/bbp_workflow/sscx_calibration_mgfix/6-O1-MPScan/6-O1-MPScan-0-5x3x2/3f543462-7a6f-4742-b62e-f03412769dbd/config.json
output: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/physiology_2023/cortexetl.output/6-O1-MPScan/6-O1-MPScan-0-5x3x2-2sims

simulations_filter:
  ca: 1.05
  depol_stdev_mean_ratio: 0.4
  desired_connected_proportion_of_invivo_frs: [0.1, 0.5]

version: 2

analysis:
  soma:
    extraction:
      report:
        type: soma
        name: soma
      neuron_classes:
        L1_EXC: { layer: [ 1 ], synapse_class: [ EXC ] }
        L23_EXC: { layer: [ 2, 3 ], synapse_class: [ EXC ] }
        L4_EXC: { layer: [ 4 ], synapse_class: [ EXC ] }
        L5_EXC: { layer: [ 5 ], synapse_class: [ EXC ] }
        L6_EXC: { layer: [ 6 ], synapse_class: [ EXC ] }
        L1_INH: { layer: [ 1 ], synapse_class: [ INH ] }
        L23_INH: { layer: [ 2, 3 ], synapse_class: [ INH ] }
        L4_INH: { layer: [ 4 ], synapse_class: [ INH ] }
        L5_INH: { layer: [ 5 ], synapse_class: [ INH ] }
        L6_INH: { layer: [ 6 ], synapse_class: [ INH ] }
        # ALL_INH: { synapse_class: [ INH ], $limit: null }
        # ALL_EXC: { synapse_class: [ EXC ], $limit: null }
        # ALL: { $limit: null }
      # limit: 10
      target: hex0
      windows:
        w1: { bounds: [ 1500, 2000 ], window_type: spontaneous, t_step: 1.0 }
        # w2: { bounds: [ 10, 70 ], initial_offset: 10, t_step: 0.5 }
    features:
      - type: multi
        groupby: [ simulation_id, circuit_id, neuron_class, window ]
        function: blueetl.external.soma.calculate_features.calculate_features_by_simulation_circuit_neuron_class_window
      - type: multi
        groupby: [ simulation_id, circuit_id ]
        function: blueetl.external.soma.calculate_features.calculate_features_by_simulation_circuit

    custom:
      independent_variables: ["ca", "desired_connected_proportion_of_invivo_frs", "depol_stdev_mean_ratio"]

  hex0_spikes:
    extraction:

      report: {type: spikes}
      limit: null
      target: hex0

      neuron_classes:
        L1_EXC: { layer: [1], synapse_class: [EXC] }
        L23_EXC: { layer: [2, 3], synapse_class: [EXC] }
        L4_EXC: { layer: [4], synapse_class: [EXC] }
        L5_EXC: { layer: [5], synapse_class: [EXC] }
        L6_EXC: { layer: [6], synapse_class: [EXC] }
        L1_INH: { layer: [1], synapse_class: [INH] }
        L23_INH: { layer: [2, 3], synapse_class: [INH] }
        L4_INH: { layer: [4], synapse_class: [INH] }
        L5_INH: { layer: [5], synapse_class: [INH] }
        L6_INH: { layer: [6], synapse_class: [INH] }

      windows:
        unconn_2nd_half: { bounds: [ 1500, 2000 ], window_type: spontaneous }

    custom:
      independent_variables: ["ca", "desired_connected_proportion_of_invivo_frs", "depol_stdev_mean_ratio"]

  

        
