simulation_campaign: /gpfs/bbp.cscs.ch/project/proj83/scratch/bbp_workflow/sscx_calibration_mgfix/6-O1-MPScan/6-O1-MPScan-0-5x3x2/3f543462-7a6f-4742-b62e-f03412769dbd/config.json
output: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/physiology_2023/cortexetl.output/6-O1-MPScan/6-O1-MPScan-0-5x3x2-etl3
version: 3

# Campaign
#   Ca: 1.05, 1.1
#   R_OU: 0.2, 0.3, 0.4
#   P_FR: 0.1, 0.3, 0.5, 0.7, 0.9

# simulations_filter:
#   ca: [1.05, 1.1]
#   depol_stdev_mean_ratio: [0.2, 0.4]
#   desired_connected_proportion_of_invivo_frs: [0.1, 0.9]

analysis:
  soma:
    extraction:
      report: {type: soma, name: soma}
      neuron_classes:
        L23_EXC:
          query:
            layer: ["2", "3"]
            synapse_class: [EXC]
        L4_EXC:
          query:
            layer: ["4"]
            synapse_class: [EXC]
        L5_EXC:
          query:
            layer: ["5"]
            synapse_class: [EXC]
        L6_EXC:
          query:
            layer: ["6"]
            synapse_class: [EXC]
        L1_INH:
          query:
            layer: ["1"]
            synapse_class: [INH]
        L23_INH:
          query:
            layer: ["2", "3"]
            synapse_class: [INH]
        L4_INH:
          query:
            layer: ["4"]
            synapse_class: [INH]
        L5_INH:
          query:
            layer: ["5"]
            synapse_class: [INH]
        L6_INH:
          query:
            layer: ["6"]
            synapse_class: [INH]
      limit: 100
      windows:
        w1:
          bounds: [1500, 6500]
          window_type: spontaneous
          t_step: 1.0
      node_set: hex0
    features:
    - type: multi
      groupby: [simulation_id, circuit_id]
      function: blueetl.external.soma.calculate_features.calculate_features_by_simulation_circuit
    custom:
      independent_variables: [ca, desired_connected_proportion_of_invivo_frs, depol_stdev_mean_ratio]
  hex0_spikes:
    extraction:
      report: {type: spikes}
      limit: null
      neuron_classes:
        L23_EXC:
          query:
            layer: ["2", "3"]
            synapse_class: [EXC]
        L4_EXC:
          query:
            layer: ["4"]
            synapse_class: [EXC]
        L5_EXC:
          query:
            layer: ["5"]
            synapse_class: [EXC]
        L6_EXC:
          query:
            layer: ["6"]
            synapse_class: [EXC]
        L1_INH:
          query:
            layer: ["1"]
            synapse_class: [INH]
        L23_INH:
          query:
            layer: ["2", "3"]
            synapse_class: [INH]
        L4_INH:
          query:
            layer: ["4"]
            synapse_class: [INH]
        L5_INH:
          query:
            layer: ["5"]
            synapse_class: [INH]
        L6_INH:
          query:
            layer: ["6"]
            synapse_class: [INH]
        ALL_INH:
          query:
            synapse_class: [INH]
          limit: null
        ALL_EXC:
          query:
            synapse_class: [EXC]
          limit: null
        ALL: {limit: null}
      windows:
        w1:
          bounds: [1500, 6500]
          window_type: spontaneous
          t_step: 1.0
        unconn_2nd_half:
          bounds: [500, 1000]
          window_type: spontaneous
        conn_spont:
          bounds: [1500, 6500]
          window_type: spontaneous
      node_set: hex0
    features:
    - type: multi
      groupby: [simulation_id, circuit_id, neuron_class, window]
      function: cortexetl.calculate_features.calculate_features_multi
      params:
        export_all_neurons: true
        histograms:
          1ms:
            bin_size: 1.0
            smoothing:
              1sd: {smoothing_type: Gaussian, kernel_sd: 1.0}
              3sd: {smoothing_type: Gaussian, kernel_sd: 3.0}
          3ms:
            bin_size: 3.0
            smoothing:
              1sd: {smoothing_type: Gaussian, kernel_sd: 1.0}
    custom:
      plot_multi_sim_analysis: true
      plot_rasters: true
      create_raster_videos: true
      independent_variables: [ca, desired_connected_proportion_of_invivo_frs, depol_stdev_mean_ratio]
      vivo_frs: {L1_INH: 1.5, L23_EXC: 0.07, L23_INH: 0.961, L4_EXC: 0.619, L4_INH: 1.184,
        L5_EXC: 1.252, L5_INH: 2.357, L6_EXC: 0.47, L6_INH: 1.5}
      heatmap_dims: {hor_key: ca, ver_key: none, x_key: desired_connected_proportion_of_invivo_frs,
        y_key: depol_stdev_mean_ratio}
      raster_windows:
      - {conn_spont: 5.0}
      fr_comparison_pairs:
      - [unconn_2nd_half, conn_spont]
      - [desired_connected_fr, conn_spont]
      - [desired_unconnected_fr, unconn_2nd_half]
      - [connection_fr_increase, connection_fr_error]
      desired_connected_fr_key: desired_connected_fr
      desired_unconnected_fr_key: desired_unconnected_fr
      ei_corr_r_val_limits: [0.15, 0.4]
      depol_bc_key: gExc
      fr_analysis_neuron_classes_constant: LAYER_EI_NEURON_CLASSES
      vertical_plot_seperate_groupings: E_AND_I_SEPERATE_GROUPINGS
      input_conductance_by_neuron_class_parquet: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/physiology_2023/reference_data_do_not_delete/input_conductance_by_neuron_class_EI.parquet
