---
simulation_campaign: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/simulations/elife_sscx_physiology_2024/6-O1-MPScan/6-O1-MPScan-0-5x3x2/3f543462-7a6f-4742-b62e-f03412769dbd/config.json
output: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/physiology_2023/cortex_etl_output/6-O1-MPScan/6-O1-MPScan-0-5x3x2

version: 2

analysis:
  soma:
    extraction:
      report:
        type: soma
        name: soma
      neuron_classes:
        L1_EXC: { layer: [ 1 ], synapse_class: [ EXC ] }
        L23_EXC: { layer: [ 2, 3 ], synapse_class: [ EXC ] }
        L4_EXC: { layer: [ 4 ], synapse_class: [ EXC ] }
        L5_EXC: { layer: [ 5 ], synapse_class: [ EXC ] }
        L6_EXC: { layer: [ 6 ], synapse_class: [ EXC ] }
        L1_INH: { layer: [ 1 ], synapse_class: [ INH ] }
        L23_INH: { layer: [ 2, 3 ], synapse_class: [ INH ] }
        L4_INH: { layer: [ 4 ], synapse_class: [ INH ] }
        L5_INH: { layer: [ 5 ], synapse_class: [ INH ] }
        L6_INH: { layer: [ 6 ], synapse_class: [ INH ] }
      limit: 100
      target: hex0
      windows:
        w1: { bounds: [ 1500, 2000 ], window_type: spontaneous, t_step: 1.0 }
        # w2: { bounds: [ 10, 70 ], initial_offset: 10, t_step: 0.5 }
    features:
      # - type: multi
      #   groupby: [ simulation_id, circuit_id, neuron_class, window ]
      #   function: blueetl.external.soma.calculate_features.calculate_features_by_simulation_circuit_neuron_class_window
      - type: multi
        groupby: [ simulation_id, circuit_id ]
        function: blueetl.external.soma.calculate_features.calculate_features_by_simulation_circuit

    custom:
      independent_variables: ["ca", "desired_connected_proportion_of_invivo_frs", "depol_stdev_mean_ratio"]

  hex0_spikes:
    extraction:

      report: {type: spikes}
      limit: null
      target: hex0

      neuron_classes:
        L1_EXC: { layer: [1], synapse_class: [EXC] }
        L23_EXC: { layer: [2, 3], synapse_class: [EXC] }
        L4_EXC: { layer: [4], synapse_class: [EXC] }
        L5_EXC: { layer: [5], synapse_class: [EXC] }
        L6_EXC: { layer: [6], synapse_class: [EXC] }
        L1_INH: { layer: [1], synapse_class: [INH] }
        L23_INH: { layer: [2, 3], synapse_class: [INH] }
        L4_INH: { layer: [4], synapse_class: [INH] }
        L5_INH: { layer: [5], synapse_class: [INH] }
        L6_INH: { layer: [6], synapse_class: [INH] }
        ALL_INH: { synapse_class: [INH], $limit: null }
        ALL_EXC: { synapse_class: [EXC], $limit: null }
        ALL: { $limit: null }

      windows:
        w1: { bounds: [ 1500, 2000 ], window_type: spontaneous, t_step: 1.0 }
        unconn_2nd_half: { bounds: [ 500, 1000 ], window_type: spontaneous }
        conn_spont: { bounds: [ 1500, 6500 ], window_type: spontaneous }

    features:
    - type: multi
      groupby: [simulation_id, circuit_id, neuron_class, window]
      function: cortexetl.calculate_features.calculate_features_multi
      params:
        export_all_neurons: true
        histograms:
          1ms:
            bin_size: 1.0
            smoothing:
              1sd: {smoothing_type: Gaussian, kernel_sd: 1.0}
              3sd: {smoothing_type: Gaussian, kernel_sd: 3.0}
          3ms:
            bin_size: 3.0
            smoothing:
              1sd: {smoothing_type: Gaussian, kernel_sd: 1.0}

    custom:
      plot_multi_sim_analysis: true
      plot_rasters: true
      create_raster_videos: true
      
      independent_variables: ["ca", "desired_connected_proportion_of_invivo_frs", "depol_stdev_mean_ratio"]
      vivo_frs: {L1_INH: 1.5, L23_EXC: 0.07, L23_INH: 0.961, L4_EXC: 0.619, L4_INH: 1.184, L5_EXC: 1.252, L5_INH: 2.357, L6_EXC: 0.47, L6_INH: 1.5}
      heatmap_dims: {hor_key: "ca", ver_key: "none", x_key: "desired_connected_proportion_of_invivo_frs", y_key: "depol_stdev_mean_ratio"}
      raster_windows: [{conn_spont: 5.0}]
      fr_comparison_pairs: [['unconn_2nd_half', 'conn_spont'], ['desired_connected_fr', 'conn_spont'], ['desired_unconnected_fr', 'unconn_2nd_half'], ['connection_fr_increase', 'connection_fr_error']]
      desired_connected_fr_key: desired_connected_fr
      desired_unconnected_fr_key: desired_unconnected_fr
      ei_corr_r_val_limits: [0.15, 0.4]
      depol_bc_key: gExc

      fr_analysis_neuron_classes_constant: LAYER_EI_NEURON_CLASSES
      vertical_plot_seperate_groupings: E_AND_I_SEPERATE_GROUPINGS
      input_conductance_by_neuron_class_parquet: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/physiology_2023/reference_data_do_not_delete/input_conductance_by_neuron_class_EI.parquet

      

