version: 3
simulation_campaign: /gpfs/bbp.cscs.ch/project/proj83/scratch/home/isbister/post_physiology_2023/sim_data/campaigns/schneider_mizell/0_recalibration/1_0_whisker_deflections_test_28_3_24/c933b47f-a390-4012-bfbf-da9c7c411cca/config.json
output: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/post_physiology_2023/cortex_etl_output/campaigns/schneider_mizell/1_whisker_deflections/1_0_whisker_deflections_test_28_3_24/
clear_cache: false
analysis:
  hex0_spikes:
    extraction:
      report: {type: spikes}
      limit: null
      neuron_classes:
        L23_EXC:
          query:
            layer: [2, 3]
            synapse_class: [EXC]
        L4_EXC:
          query:
            layer: [4]
            synapse_class: [EXC]
        L5_EXC:
          query:
            layer: [5]
            synapse_class: [EXC]
        L6_EXC:
          query:
            layer: [6]
            synapse_class: [EXC]
        L1_INH:
          query:
            layer: [1]
            synapse_class: [INH]
        L23_INH:
          query:
            layer: [2, 3]
            synapse_class: [INH]
        L4_INH:
          query:
            layer: [4]
            synapse_class: [INH]
        L5_INH:
          query:
            layer: [5]
            synapse_class: [INH]
        L6_INH:
          query:
            layer: [6]
            synapse_class: [INH]
        ALL_INH:
          query:
            synapse_class: [INH]
          limit: null
        ALL_EXC:
          query:
            synapse_class: [EXC]
          limit: null
        ALL: {limit: null}
      windows:
        unconn_2nd_half:
          bounds: [500, 1000]
          window_type: spontaneous
        conn_spont:
          bounds: [1500, 2500]
          window_type: spontaneous
        evoked_SOZ_25ms: 
          bounds: [ 0, 25 ]
          initial_offset: 1500
          n_trials: 2
          trial_steps_value: 1000
          window_type: evoked_stimulus_onset_zeroed
        evoked_SOZ_250ms: 
          bounds: [ -50, 250 ]
          initial_offset: 1500
          n_trials: 2
          trial_steps_value: 500
          window_type: evoked_stimulus_onset_zeroed
      population: S1nonbarrel_neurons
      node_set: hex0
    features:
    - type: multi
      groupby: [simulation_id, circuit_id, neuron_class, window]
      function: cortex_etl.calculate_features.calculate_features_multi
      params:
        export_all_neurons: true
        histograms:
          1ms:
            bin_size: 1.0
            smoothing:
              1sd: {smoothing_type: Gaussian, kernel_sd: 1.0}
              3sd: {smoothing_type: Gaussian, kernel_sd: 3.0}
          3ms:
            bin_size: 3.0
            smoothing:
              1sd: {smoothing_type: Gaussian, kernel_sd: 1.0}
          5ms:
            bin_size: 5.0
            smoothing:
              1sd: {smoothing_type: Gaussian, kernel_sd: 1.0}

    - type: multi
      groupby: [simulation_id, circuit_id, neuron_class, window]
      function: barreletl.features.calculate_features_by_neuron_class
      windows: [evoked_SOZ_250ms]
      params:
        latency:
          params: { onset: false }
        decay:
          params:
            ratio: [0.25, 0.5, 0.75, 1.0]
      params_product:
        baseline_PSTH:
          - params: { bin_size: 0.5, sigma: 0, offset: -6 }
          - params: { bin_size: 0.5, sigma: 2, offset: -6 }
          - params: { bin_size: 0.5, sigma: 4, offset: -6 }
          - params: { bin_size: 1, sigma: 0, offset: -6 }
          - params: { bin_size: 1, sigma: 1, offset: -6 }
          - params: { bin_size: 1, sigma: 2, offset: -6 }
          - params: { bin_size: 1, sigma: 3, offset: -6 }

    - type: multi
      groupby: [simulation_id, circuit_id, neuron_class, window]
      function: barreletl.features.calculate_features_by_neuron_class
      windows: [evoked_SOZ_250ms]
      params:
        psth_name: smoothed_PSTH
        smoothed_PSTH:
          params: { bin_size: 1, sigma: 0, offset: -6 }
        mean_psth:
          params: { t_stim: 0 }
        max_psth:
          params: { t_stim: 0 }


    custom:
      plot_multi_sim_analysis: true
      plot_rasters: true
      create_raster_videos: true
      compare_to_missing_synapses: true
      extract_fr_df: false
      compare_campaigns: false
      plot_multi_sim_analysis_for_comparison_campaigns: false
      create_multi_sim_summary_pdfs: false
      independent_variables: [ca, desired_connected_proportion_of_invivo_frs, depol_stdev_mean_ratio, vpm_pct]
      vivo_frs: {L1_INH: 1.5, L23_EXC: 0.07, L23_INH: 0.961, L4_EXC: 0.619, L4_INH: 1.184,
        L5_EXC: 1.252, L5_INH: 2.357, L6_EXC: 0.47, L6_INH: 1.5}
      heatmap_dims: {hor_key: ca, ver_key: none, x_key: desired_connected_proportion_of_invivo_frs,
        y_key: depol_stdev_mean_ratio}
      raster_windows:
      - {conn_spont: 3.6}
      fr_comparison_pairs:
      - [unconn_2nd_half, conn_spont]
      - [desired_connected_fr, conn_spont]
      - [desired_unconnected_fr, unconn_2nd_half]
      - [connection_fr_increase, connection_fr_error]
      desired_connected_fr_key: desired_connected_fr
      desired_unconnected_fr_key: desired_unconnected_fr
      ei_corr_r_val_limits: [0.15, 0.4]
      depol_bc_key: gExc
      campaign_short_name: schneider_mizell_transfer_1stIter
      fr_df_name: connection_data_from_schneider_mizell_0_0_recalibration_6thIter_20_3_24.parquet
      fr_df_windows: [conn_spont]
      fr_analysis_neuron_classes_constant: LAYER_EI_NEURON_CLASSES
      vertical_plot_seperate_groupings: E_AND_I_SEPERATE_GROUPINGS
      input_conductance_by_neuron_class_parquet: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/physiology_2023/reference_data_do_not_delete/input_conductance_by_neuron_class_EI.parquet

      evoked_mask_comparison_dataset: ReyesPuerta
      vivo_ratios_df: /gpfs/bbp.cscs.ch/project/proj100/analysis/vivo_ratios_svoboda_reyes.feather
      vivo_ratios_dataset: reyesp
      vivo_df: /gpfs/bbp.cscs.ch/project/proj147/home/isbister/rp/dfs/invivo_psth_means_plot_ready.f
      evoked_window_for_custom_post_analysis: evoked_SOZ_250ms
      
  # hex_O1_spikes:
  #   extraction:
  #     report: {type: spikes}
  #     neuron_classes:
  #       ALL: {limit: null}
  #     limit: null
  #     windows:
  #       conn_spont:
  #         bounds: [1500, 6500]
  #         window_type: spontaneous
  #     population: S1nonbarrel_neurons
  #     node_set: hex_O1
  #   custom:
  #     create_flatspace_videos: false
  #     independent_variables: [ca, desired_connected_proportion_of_invivo_frs, depol_stdev_mean_ratio]
  #     flatmap: /gpfs/bbp.cscs.ch/project/proj83/home/bolanos/BB_Rat_SSCX_flatmap_v2.nrrd
  #     flatspace_videos:
  #       fsv_3: {window: conn_spont, t_step: 100.0, n_spatial_bins: 1500, temporal_smoothing_sigma: 1.0,
  #         delete_images: false, stim_anal: null}
