version: 3
simulation_campaign: /gpfs/bbp.cscs.ch/project/proj83/scratch/home/isbister/post_physiology_2023/sim_data/0_InterneuronsCalibration/0_InterneuronsCalibration_1stIteration_Ca11_Rou01_30_8_23/f742def7-b7ba-456a-b7f1-f30c8e08eb8e/config.json
output: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/post_physiology_2023/cortex_etl_output/0_InterneuronsCalibration/0_InterneuronsCalibration_1stIteration_Ca11_Rou01_30_8_23
clear_cache: false
analysis:
  hex0_spikes:
    extraction:
      report: {type: spikes}
      limit: null
      neuron_classes:
        L23_EXC:
          query:
            layer: [2, 3]
            synapse_class: [EXC]
        L4_EXC:
          query:
            layer: [4]
            synapse_class: [EXC]
        L5_EXC:
          query:
            layer: [5]
            synapse_class: [EXC]
        L6_EXC:
          query:
            layer: [6]
            synapse_class: [EXC]
        L1_INH:
          query:
            layer: [1]
            synapse_class: [INH]
        L23_INH:
          query:
            layer: [2, 3]
            synapse_class: [INH]
        L4_INH:
          query:
            layer: [4]
            synapse_class: [INH]
        L5_INH:
          query:
            layer: [5]
            synapse_class: [INH]
        L6_INH:
          query:
            layer: [6]
            synapse_class: [INH]
        
        L1_5HT3aR:
          query:
            layer: [1]
            synapse_class: [INH]

        L23_PV:
          query:
          - {layer: [2, 3], mtype: [L23_LBC, L23_NBC, L23_CHC]}
        L23_SST:
          query:
          - {layer: [2, 3], mtype: [L23_MC]}
          - {layer: [2, 3], mtype: [L23_DBC, L23_BTC], etype: [cACint]}
        L23_5HT3aR:
          query:
            - {layer: [2, 3], mtype: [L23_SBC, L23_BP, L23_NGC]}
            - {layer: [2, 3], mtype: [L23_DBC, L23_BTC], etype: [bNAC, bAC, cNAC, dNAC, cIR, bIR, bSTUT]}

        L4_PV:
          query:
          - {layer: [4], mtype: [L4_LBC, L4_NBC, L4_CHC]}
        L4_SST:
          query:
          - {layer: [4], mtype: [L4_MC]}
          - {layer: [4], mtype: [L4_DBC, L4_BTC], etype: [cACint]}
        L4_5HT3aR:
          query:
            - {layer: [4], mtype: [L4_SBC, L4_BP, L4_NGC]}
            - {layer: [4], mtype: [L4_DBC, L4_BTC], etype: [bNAC, bAC, cNAC, dNAC, cIR, bIR, bSTUT]}

        L5_PV:
          query:
          - {layer: [5], mtype: [L5_LBC, L5_NBC, L5_CHC]}
        L5_SST:
          query:
          - {layer: [5], mtype: [L5_MC]}
          - {layer: [5], mtype: [L5_DBC, L5_BTC], etype: [cACint]}
        L5_5HT3aR:
          query:
            - {layer: [5], mtype: [L5_SBC, L5_BP, L5_NGC]}
            - {layer: [5], mtype: [L5_DBC, L5_BTC], etype: [bNAC, bAC, cNAC, dNAC, cIR, bIR, bSTUT]}

        L6_PV:
          query:
          - {layer: [6], mtype: [L6_LBC, L6_NBC, L6_CHC]}
        L6_SST:
          query:
          - {layer: [6], mtype: [L6_MC]}
          - {layer: [6], mtype: [L6_DBC, L6_BTC], etype: [cACint]}
        L6_5HT3aR:
          query:
            - {layer: [6], mtype: [L6_SBC, L6_BP, L6_NGC]}
            - {layer: [6], mtype: [L6_DBC, L6_BTC], etype: [bNAC, bAC, cNAC, dNAC, cIR, bIR, bSTUT]}

        ALL_INH:
          query:
            synapse_class: [INH]
          limit: null
        ALL_EXC:
          query:
            synapse_class: [EXC]
          limit: null
        ALL: {limit: null}
      windows:
        unconn_2nd_half:
          bounds: [500, 1000]
          window_type: spontaneous
        conn_spont:
          bounds: [1500, 6500]
          window_type: spontaneous
        full_sim:
          bounds: [0, 6500]
          window_type: spontaneous
      population: All
      node_set: hex0
    features:
    - type: multi
      groupby: [simulation_id, circuit_id, neuron_class, window]
      function: cortex_etl.calculate_features.calculate_features_multi
      params:
        export_all_neurons: true
        histograms:
          1ms:
            bin_size: 1.0
            smoothing:
              1sd: {smoothing_type: Gaussian, kernel_sd: 1.0}
              3sd: {smoothing_type: Gaussian, kernel_sd: 3.0}
          3ms:
            bin_size: 3.0
            smoothing:
              1sd: {smoothing_type: Gaussian, kernel_sd: 1.0}
          5ms:
            bin_size: 5.0
            smoothing:
              1sd: {smoothing_type: Gaussian, kernel_sd: 1.0}
    custom:
      plot_multi_sim_analysis: true
      plot_rasters: true
      create_raster_videos: true
      compare_to_missing_synapses: false
      extract_fr_df: false
      compare_campaigns: false
      plot_multi_sim_analysis_for_comparison_campaigns: false
      create_multi_sim_summary_pdfs: false
      independent_variables: [ca, desired_connected_proportion_of_invivo_frs, depol_stdev_mean_ratio]
      vivo_frs: {L1_INH: 1.5, L1_5HT3aR: 1.500, 
                L23_EXC: 0.070, L23_INH: 0.961, L23_PV: 0.961, L23_SST: 0.961, L23_5HT3aR: 0.961, 
                L4_EXC: 0.619, L4_INH: 1.184, L4_PV: 1.184, L4_SST: 1.184, L4_5HT3aR: 1.184, 
                L5_EXC: 1.252, L5_INH: 2.357, L5_PV: 2.357, L5_SST: 2.357, L5_5HT3aR: 2.357, 
                L6_EXC: 0.470, L6_INH: 1.5, L6_PV: 1.500, L6_SST: 1.500, L6_5HT3aR: 1.500}
      heatmap_dims: {hor_key: ca, ver_key: none, x_key: desired_connected_proportion_of_invivo_frs,
        y_key: depol_stdev_mean_ratio}
      raster_windows:
      - {full_sim: 3.6}
      - {conn_spont: 3.6}
      fr_comparison_pairs:
      - [unconn_2nd_half, conn_spont]
      - [desired_connected_fr, conn_spont]
      - [desired_unconnected_fr, unconn_2nd_half]
      desired_connected_fr_key: desired_connected_fr
      desired_unconnected_fr_key: desired_unconnected_fr
      fr_analysis_neuron_classes_constant: LAYER_E_AND_I_SUB_POP_NEURON_CLASSES
      vertical_plot_seperate_groupings: E_AND_I_SUB_POP_SEPERATE_GROUPINGS
      input_conductance_by_neuron_class_parquet: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/physiology_2023/reference_data_do_not_delete/input_conductance_by_neuron_class_EandISubPop.parquet
      ei_corr_r_val_limits: [0.15, 0.4]
      depol_bc_key: gExc
      campaign_short_name: Transfer 3rd conn.
      fr_df_name: connection_data_from_mgfix_2-PfrTransfer-6-3rdConnectionRemaining_15-11-22.parquet
  hex_O1_spikes:
    extraction:
      report: {type: spikes}
      neuron_classes:
        ALL: {limit: null}
      limit: null
      windows:
        conn_spont:
          bounds: [1500, 6500]
          window_type: spontaneous
      population: All
      node_set: hex_O1
    custom:
      create_flatspace_videos: false
      independent_variables: [ca, desired_connected_proportion_of_invivo_frs, depol_stdev_mean_ratio]
      flatmap: /gpfs/bbp.cscs.ch/project/proj83/home/bolanos/BB_Rat_SSCX_flatmap_v2.nrrd
      flatspace_videos:
        fsv_3: {window: conn_spont, t_step: 100.0, n_spatial_bins: 1500, temporal_smoothing_sigma: 1.0,
          delete_images: false, stim_anal: null}
