version: 3
simulation_campaign: /gpfs/bbp.cscs.ch/project/proj83/scratch/home/isbister/post_physiology_2023/sim_data/campaigns/spikesorting_stimulus_tests/8_spikesorting_stimulus_test_neuropixels_13-4-24/8_spikesorting_stimulus_test_neuropixels_13-4-24__8slc_100f_72r_250t_200ms_0/12c5ef9a-1f3b-4b18-b3f5-ec6a417f645c/config.json
output: /gpfs/bbp.cscs.ch/project/proj83/home/isbister/post_physiology_2023/cortex_etl_output/campaigns/spikesorting_stimulus_tests/8_spikesorting_stimulus_test_neuropixels_13-4-24/8_spikesorting_stimulus_test_neuropixels_13-4-24__8slc_100f_72r_250t_200ms_0
clear_cache: false
analysis:
  hex0_spikes:
    extraction:
      report: {type: spikes}
      limit: null
      node_set: hex0
      neuron_classes:
        L1_EXC:
          query:
            layer: ["1"]
            synapse_class: [EXC]
        L23_EXC:
          query:
            layer: ["2", "3"]
            synapse_class: [EXC]
        L4_EXC:
          query:
            layer: ["4"]
            synapse_class: [EXC]
        L5_EXC:
          query:
            layer: ["5"]
            synapse_class: [EXC]
        L6_EXC:
          query:
            layer: ["6"]
            synapse_class: [EXC]
        L1_INH:
          query:
            layer: ["1"]
            synapse_class: [INH]
        L23_INH:
          query:
            layer: ["2", "3"]
            synapse_class: [INH]
        L4_INH:
          query:
            layer: ["4"]
            synapse_class: [INH]
        L5_INH:
          query:
            layer: ["5"]
            synapse_class: [INH]
        L6_INH:
          query:
            layer: ["6"]
            synapse_class: [INH]
        L23_PV:
          query:
            layer: ["2", "3"]
            mtype: [L23_LBC, L23_NBC, L23_CHC]
        L4_PV:
          query:
            layer: ["4"]
            mtype: [L4_CHC, L4_NBC, L4_LBC]
        L5_PV:
          query:
            layer: ["5"]
            mtype: [L5_CHC, L5_LBC, L5_NBC]
        L6_PV:
          query:
            layer: ["6"]
            mtype: [L6_LBC, L6_CHC, L6_NBC]
        L23_SST:
          query:
            layer: ["2", "3"]
            mtype: [L23_BTC, L23_NGC, L23_SBC, L23_MC, L23_DBC]
        L4_SST:
          query:
            layer: ["4"]
            mtype: [L4_NGC, L4_DBC, L4_SBC, L4_BTC, L4_MC]
        L5_SST:
          query:
            layer: ["5"]
            mtype: [L5_SBC, L5_BTC, L5_DBC, L5_NGC, L5_MC]
        L6_SST:
          query:
            layer: ["6"]
            mtype: [L6_BTC, L6_NGC, L6_MC, L6_SBC, L6_DBC]
        L23_5HT3aR:
          query:
            layer: ["2", "3"]
            mtype: [L23_BP]
        L4_5HT3aR:
          query:
            layer: ["4"]
            mtype: [L4_BP]
        L5_5HT3aR:
          query:
            layer: ["5"]
            mtype: [L5_BP]
        L6_5HT3aR:
          query:
            layer: ["6"]
            mtype: [L6_BP]


      windows:
        unconn_2nd_half:
          bounds: [500, 1000]
          window_type: spontaneous
      
custom:
  standard_key: gt
  # window_groupings: *id001
